const mongoose = require("mongoose");

const mockInterviewSchema = new mongoose.Schema(
  {
    /* Who is taking the mock interview */
    userId: {
      type: String,           // Firebase UID or "anonymous"
      required: true,
    },

    /* Two OA questions we serve to the candidate */
    questions: [
      {
        text:     String,
        category: String,
      },
    ],

    /* Local path or Cloud URL of the recorded video (set after upload) */
    videoUrl: {
      type: String,
      default: "",
    },

    /* Whisper transcription text (set by transcribeVideo) */
    transcription: {
      type: String,
      default: "",
    },

    /* Step‑7 speech‑quality analysis */
    analysis: {
      wordCount: {
        type: Number,
        default: 0,
      },
      fillerWords: {
        type: Number,
        default: 0,
      },
      fluency: {             // 0‑100 score or similar metric
        type: Number,
        default: 0,
      },
      feedback: {            // autogenerated textual feedback
        type: String,
        default: "",
      },
    },
  },
  { timestamps: true }
);

module.exports = mongoose.model("MockInterview", mockInterviewSchema);
